"""add_report_links_and_entry_fields

Revision ID: b6178ccac1e2
Revises: dba0736e5893
Create Date: 2026-04-15 17:10:59.623101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6178ccac1e2'
down_revision: Union[str, None] = 'dba0736e5893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID ссылки'),
    sa.Column('token', sa.String(length=16), nullable=False, comment='Уникальный токен для URL'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID автора отчета'),
    sa.Column('week_start', sa.Date(), nullable=False, comment='Начало недели отчета'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Дата истечения ссылки'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли ссылка'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания ссылки'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_links_token'), 'report_links', ['token'], unique=True)
    op.add_column('custom_trackers', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False, comment='Системный трекер (Здоровье, Спорт, Учёба, Отдых)'))
    op.add_column('daily_entries', sa.Column('voice_file_id', sa.String(length=255), nullable=True, comment='Telegram file_id голосового/аудио сообщения'))
    op.add_column('daily_entries', sa.Column('video_file_id', sa.String(length=255), nullable=True, comment='Telegram file_id видео сообщения'))
    op.add_column('daily_entries', sa.Column('has_media', sa.Boolean(), server_default='false', nullable=False, comment='Есть ли медиа в записи (фото/голос/видео)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_entries', 'has_media')
    op.drop_column('daily_entries', 'video_file_id')
    op.drop_column('daily_entries', 'voice_file_id')
    op.drop_column('custom_trackers', 'is_default')
    op.drop_index(op.f('ix_report_links_token'), table_name='report_links')
    op.drop_table('report_links')
    # ### end Alembic commands ###
