"""initial_postgres

Revision ID: dba0736e5893
Revises: 
Create Date: 2026-04-15 00:15:40.452486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba0736e5893'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID задачи'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID получателя (Telegram user_id)'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Тип действия: send_report, send_message'),
    sa.Column('payload', sa.Text(), nullable=False, comment='JSON с данными для отправки'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='pending, processing, done, failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Ошибка при отправке'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Когда создана задача'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='Когда обработана'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_queue_status'), 'telegram_queue', ['status'], unique=False)
    op.create_index(op.f('ix_telegram_queue_user_id'), 'telegram_queue', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Telegram user ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Telegram username без @'),
    sa.Column('first_name', sa.String(length=255), nullable=True, comment='Имя в Telegram'),
    sa.Column('last_name', sa.String(length=255), nullable=True, comment='Фамилия в Telegram'),
    sa.Column('photo_url', sa.String(length=2048), nullable=True, comment='URL аватара из Telegram'),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'Europe/Moscow'"), nullable=False, comment='Часовой пояс пользователя (IANA format)'),
    sa.Column('settings', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Настройки пользователя: {"reminder_time": "21:00", "theme": "dark"}'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('custom_trackers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID трекера'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID владельца трекера'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Название трекера (например, 'Спорт', 'Английский')"),
    sa.Column('icon', sa.String(length=10), server_default=sa.text("'📊'"), nullable=False, comment='Эмодзи иконка для трекера'),
    sa.Column('target_value', sa.Integer(), nullable=True, comment='Целевое значение (например, 5 раз в неделю). Null = без цели'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False, comment='Активен ли трекер (можно архивировать)'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Порядок отображения в списке'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_trackers_user_id'), 'custom_trackers', ['user_id'], unique=False)
    op.create_table('daily_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID записи'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID владельца записи'),
    sa.Column('entry_date', sa.Date(), nullable=False, comment='Дата записи (не created_at!)'),
    sa.Column('mood', sa.Integer(), nullable=True, comment='Настроение от 1 (ужасно) до 5 (отлично)'),
    sa.Column('text', sa.Text(), nullable=True, comment='Заметки/текст дня (приватный!)'),
    sa.Column('photo_file_id', sa.String(length=255), nullable=True, comment='Telegram file_id фото дня (приватное!)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.CheckConstraint('mood BETWEEN 1 AND 5', name='ck_mood_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_date', name='uix_user_date')
    )
    op.create_index(op.f('ix_daily_entries_entry_date'), 'daily_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_daily_entries_user_id'), 'daily_entries', ['user_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID группы'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название группы'),
    sa.Column('invite_code', sa.String(length=32), nullable=False, comment='Код приглашения (8 символов)'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='ID владельца группы'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание группы'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_invite_code'), 'groups', ['invite_code'], unique=True)
    op.create_table('week_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID отчета'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID автора отчета'),
    sa.Column('week_start_date', sa.Date(), nullable=False, comment='Понедельник недели отчета'),
    sa.Column('week_end_date', sa.Date(), nullable=False, comment='Воскресенье недели отчета'),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='report_status', native_enum=False), server_default=sa.text("'draft'"), nullable=False, comment='draft или published'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='Когда отчет был опубликован'),
    sa.Column('avg_mood', sa.Float(), nullable=True, comment='Среднее настроение за неделю (1-5)'),
    sa.Column('filled_days', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Сколько дней заполнено (0-7)'),
    sa.Column('metrics_summary', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Средние значения трекеров: {"sport_avg": 4.2, ...}'),
    sa.Column('highlights', sa.Text(), nullable=True, comment='Текстовое summary от AI или пользователя'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start_date', name='uix_user_week')
    )
    op.create_index(op.f('ix_week_reports_status'), 'week_reports', ['status'], unique=False)
    op.create_index(op.f('ix_week_reports_user_id'), 'week_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_week_reports_week_start_date'), 'week_reports', ['week_start_date'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID комментария'),
    sa.Column('week_report_id', sa.Integer(), nullable=False, comment='ID отчета'),
    sa.Column('author_id', sa.BigInteger(), nullable=False, comment='ID автора комментария'),
    sa.Column('text', sa.Text(), nullable=False, comment='Текст комментария'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['week_report_id'], ['week_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_week_report_id'), 'comments', ['week_report_id'], unique=False)
    op.create_table('entry_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID'),
    sa.Column('entry_id', sa.Integer(), nullable=False, comment='ID записи дня'),
    sa.Column('tracker_id', sa.Integer(), nullable=False, comment='ID трекера'),
    sa.Column('value', sa.Integer(), nullable=False, comment='Значение от 0 (нет активности) до 5 (максимум)'),
    sa.CheckConstraint('value BETWEEN 0 AND 5', name='ck_value_range'),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracker_id'], ['custom_trackers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'tracker_id', name='uix_entry_tracker')
    )
    op.create_index(op.f('ix_entry_metrics_entry_id'), 'entry_metrics', ['entry_id'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.Integer(), nullable=False, comment='ID группы'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='ID пользователя'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='member, moderator или owner'),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Когда присоединился к группе'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uix_group_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_members')
    op.drop_index(op.f('ix_entry_metrics_entry_id'), table_name='entry_metrics')
    op.drop_table('entry_metrics')
    op.drop_index(op.f('ix_comments_week_report_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_week_reports_week_start_date'), table_name='week_reports')
    op.drop_index(op.f('ix_week_reports_user_id'), table_name='week_reports')
    op.drop_index(op.f('ix_week_reports_status'), table_name='week_reports')
    op.drop_table('week_reports')
    op.drop_index(op.f('ix_groups_invite_code'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_daily_entries_user_id'), table_name='daily_entries')
    op.drop_index(op.f('ix_daily_entries_entry_date'), table_name='daily_entries')
    op.drop_table('daily_entries')
    op.drop_index(op.f('ix_custom_trackers_user_id'), table_name='custom_trackers')
    op.drop_table('custom_trackers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_telegram_queue_user_id'), table_name='telegram_queue')
    op.drop_index(op.f('ix_telegram_queue_status'), table_name='telegram_queue')
    op.drop_table('telegram_queue')
    # ### end Alembic commands ###
